# Generated by Django 3.0.6 on 2021-05-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteUtterance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utterance', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=75)),
                ('translation', models.CharField(blank=True, max_length=200)),
                ('context', models.TextField(blank=True)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('translation', models.CharField(blank=True, max_length=100)),
                ('utterances', models.ManyToManyField(to='hilichurlian_database.CompleteUtterance')),
            ],
        ),
        migrations.AddField(
            model_name='completeutterance',
            name='words',
            field=models.ManyToManyField(to='hilichurlian_database.Word'),
        ),
    ]
