# Generated by Django 3.0.6 on 2021-05-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='utterances',
        ),
    ]
