# Generated by Django 3.0.6 on 2021-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0002_remove_word_utterances'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeutterance',
            name='translation_source',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
