# Generated by Django 4.0.1 on 2022-01-17 05:49
# MANUALLY WRITTEN
# DATA MIGRATION: https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations

from django.db import migrations
from hilichurlian_database.models import Speaker, Source # so that object_history will be created
from hilichurlian_database.templatetags import describe_url

# database already has sources and speakers in fields in CompleteUtterances
def make_existing_sources_speakers(apps, schema_editor):
	CompleteUtterance = apps.get_model('hilichurlian_database', 'CompleteUtterance')

	for utterance in CompleteUtterance.objects.all():
		# Source
		source_url = utterance.source
		# most Sources are from Version 1.0 or Version 1.5; will manually update those that are not
		version = "1.0"
		if ("Mutual_Exchange" in source_url) or ("Hilichurl_Justice" in source_url):
			version = "1.5"
		Source.objects.get_or_create(
			name = describe_url.describe_url(source_url),
			url = utterance.source,
			version = version,
		)

		# Speaker
		speaker_name = utterance.speaker
		# most Hilichurl speakers have "Hilichurl" in their name; will manually update those that do not
		speaker_type = "stud"
		if "Hilichurl" in speaker_name:
			speaker_type = "hili"
		Speaker.objects.get_or_create(
			name = speaker_name,
			type = speaker_type
		)

class Migration(migrations.Migration):

	dependencies = [
		('hilichurlian_database', '0006_speaker_word_variants_grammatical_and_more'),
	]

	operations = [
		migrations.RunPython(make_existing_sources_speakers)
	]
