# Generated by Django 4.0.1 on 2022-01-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0007_auto_20220117_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeutterance',
            old_name='source',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='historicalcompleteutterance',
            old_name='source',
            new_name='source_url',
        ),
        migrations.AlterField(
            model_name='word',
            name='variants_grammatical',
            field=models.ManyToManyField(blank=True, help_text="Select words that are grammatical variants of this word. These words must not be the same words. For example, 'mi' and 'mimi' are grammatical variants of each other.", to='hilichurlian_database.Word', verbose_name='related words'),
        ),
        migrations.AlterField(
            model_name='word',
            name='variants_same_word',
            field=models.ManyToManyField(blank=True, help_text="Select words that are exactly the same as this word and are only elongated, shortened, or otherwise similarly altered. For example, 'yaaaa' is an elongated version of 'ya' and is otherwise the exact same word.", to='hilichurlian_database.Word', verbose_name='other written forms of this word'),
        ),
    ]
