# Generated by Django 4.0.1 on 2022-01-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0008_rename_source_completeutterance_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeutterance',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hilichurlian_database.source'),
        ),
        migrations.AddField(
            model_name='historicalcompleteutterance',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hilichurlian_database.source'),
        ),
    ]
