# Generated by Django 4.0.1 on 2022-01-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0010_data_migration_assign_source_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeutterance',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='historicalcompleteutterance',
            name='source_url',
        ),
        migrations.AlterField(
            model_name='completeutterance',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hilichurlian_database.source'),
        ),
    ]
