# Generated by Django 4.0.1 on 2022-01-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0011_remove_completeutterance_source_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeutterance',
            old_name='speaker',
            new_name='speaker_name',
        ),
        migrations.RenameField(
            model_name='historicalcompleteutterance',
            old_name='speaker',
            new_name='speaker_name',
        ),
    ]
