# Generated by Django 4.0.1 on 2022-01-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0012_rename_speaker_completeutterance_speaker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeutterance',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hilichurlian_database.speaker'),
        ),
        migrations.AddField(
            model_name='historicalcompleteutterance',
            name='speaker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hilichurlian_database.speaker'),
        ),
    ]
