# Generated by Django 4.0.1 on 2022-01-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0014_data_migration_assign_speaker_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeutterance',
            name='speaker_name',
        ),
        migrations.RemoveField(
            model_name='historicalcompleteutterance',
            name='speaker_name',
        ),
        migrations.AlterField(
            model_name='completeutterance',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hilichurlian_database.speaker'),
        ),
    ]
