# Generated by Django 4.0.1 on 2022-03-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilichurlian_database', '0015_remove_completeutterance_speaker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsource',
            name='url',
            field=models.CharField(help_text='Must be the URL of an online resource documenting the utterance and its translation if provided.', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='historicalspeaker',
            name='type',
            field=models.CharField(choices=[('hili', 'Hilichurl'), ('stud', 'Student'), ('unkn', 'Unknown')], max_length=4),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(help_text='Must be the URL of an online resource documenting the utterance and its translation if provided.', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='type',
            field=models.CharField(choices=[('hili', 'Hilichurl'), ('stud', 'Student'), ('unkn', 'Unknown')], max_length=4),
        ),
    ]
